Debug: true # Set to true for development

# MySQL
DatabaseHost: 127.0.0.1
DatabasePort: 3306
DatabaseUser: root
DatabasePassword: "1234"
DatabaseName: py_homework

# Django specific
DjangoSecretKey: django-insecure-oj6m&$_92a-fbcoks6@6f)ef0^1@=bxvcpy7tw)4x6m&bm7!l^